#!/bin/bash


####### START ACTUAL CODE DOWN HERE INCLUDING USAGE! #####


### show usage if we don't give at least 1 command-line arguments when we call the script ###
if [ "$1" == "" ]
	then
	    echo "-----------------------------------------------------------------"
	    echo "USAGE:"
	    echo "Enter the BAM file you would like to analyse on the command line and the prefix of the Filename"
	    echo "Tool used is GATK Unified Genotyper with ploidy set to 1"
	    echo "UnifiedGenotyper --> java -jar ~/bin/GATK3.30/GenomeAnalysisTK.jar -T UnifiedGenotyper -R Reference.fasta -I $1  -o $1.all.vcf";
	    echo "example usage:"
	    echo "GATK_Realigner.sh WAI321.vcf WAI321"
	    echo "-----------------------------------------------------------------"
	    exit 1
	else
	 echo "Computing variants for: $@"	 
	java -Xmx10g -jar ~/bin/GATK/GenomeAnalysisTK.jar -T VariantRecalibrator -l debug \
	-R /Users/meganm/Genomes/IPO323/Mycosphaerella_graminicola.allmasked.fa \
	--input $1 \
	-resource:known=true,training=true,truth=true,prior=6 /Users/meganm/Genomes/GATK_Variant_Detection/knownsnps.vcf \
	-an DP -an QD -an FS \
	-mode SNP \
	-recalFile $2.SNPs.recal \
	-tranchesFile $2.SNPs.tranches\
	-rscriptFile recal.SNP.plots.R
	
	java -Xmx10g -jar ~/bin/GATK/GenomeAnalysisTK.jar -T ApplyRecalibration \
	-R /Users/meganm/Genomes/IPO323/Mycosphaerella_graminicola.allmasked.fa \
	--input $1 \
	-mode SNP \
	-recalFile $2.SNPs.recal \
	-tranchesFile $2.SNPs.tranches \
	-o recal.SNPs.vcf \
	
	
#	java -Xmx10g -jar ~/bin/GATK3.30/GenomeAnalysisTK.jar -T VariantRecalibrator \
#	-R /Users/meganm/Genomes/IPO323/Mycosphaerella_graminicola.allmasked.fa \
#	--input recal.SNPs.vcf \
#	-resource:known=false,training=true,truth=true,prior=15 /Users/meganm/Genomes/GATK_Variant_Detection/knownsnps.vcf \
#	-an DP -an QD -an FS -an MQRankSum \
#	-ts_filter_level 99 --maxGaussians 4\
#	-mode INDEL\
#	-recalFile $2.INDEL.recal \
#	-tranchesFile $2.INDEL.tranches\
#	-rscriptFile totalrecal.plots.R
#	
#	java -Xmx10g -jar ~/bin/GATK3.30/GenomeAnalysisTK.jar -T ApplyRecalibration \
#	-R /Users/meganm/Genomes/IPO323/Mycosphaerella_graminicola.allmasked.fa \
#	--input recal.SNPs.vcf \
#	-mode INDEL \
#	-recalFile $2.INDEL.recal \
#	-tranchesFile $2.INDEL.tranches \
#	-ts_filter_level 99.0

fi
